
```{r libraries}
source(here::here("r", "libraries.r"))

```

```{r locations}
dpad <- r"(E:\data\cornell_pad\)"
dschools <- path(dpad, "schools")
dnysed <- r"(E:\data\nyschools\)"

```

```{r districts}

ccsid <- "641610"
gwid <- "640801"
saraid <- "521800"
schuyid <- "521701"
locals <- c(ccsid, gwid, saraid, schuyid)

```

```{r getdata}
files <- c("basic", 
           "demographics", "demowide",
           "elamath",
           "enroll", "enrollwide",
           "finance", "finwide",
           "finsedwide", "finsedvmap",
           "graduation", "subgroups")
for(file in files){
  print(file)
  assign(file, readRDS(here::here("data", paste0(file, ".rds"))))
}

check <- finsedwide |>
  select(districtid, dname, syear, subtotexp, fbtchretire, fbemphealth, fbtotal, dcaadm) |> 
  left_join(enrollwide |> 
              mutate(syear=year + 1) |> 
              select(districtid, syear, enroll=total),
            by = c("districtid", "syear"))


```

```{r enrollment}
#| output: true
check |> 
  filter(districtid==ccsid) |> 
  pivot_longer(cols=c(dcaadm, enroll)) |> 
  ggplot(aes(syear, value, colour=name)) +
  geom_line() +
  geom_point()
```

Expenditures per pupil

```{r}
#| label: test
#| output: true

check |> 
  mutate(xfb=subtotexp - fbtotal,
         across(c(xfb, starts_with("fb")),
                ~ .x / enroll))

```
